# The general help url for your plugin. Will be displayed on all admin pages.
url: https://github.com/moay/sensebox-loxberry

# Optional: Provide a helo view for your admin pages.
# Stick to this format:
#   [Route name]: [Twig file in your views folder]
pages:
  settings: help/default.html.twig
  senseboxTest: help/default.html.twig
