# The general help url for your plugin. Will be displayed on all admin pages.
url: https://google.com

# Optional: Provide a helo view for your admin pages.
# Stick to this format:
#   [Route name]: [Twig file in your views folder]
pages:
  home: help/home.html.twig
