settings:
  route: '/'
  controller: 'LoxBerryPoppinsPlugin\Controller\SettingsController'
  action: 'settingsPage'
storeSettings:
  route: '/store-settings'
  method: 'POST'
  controller: 'LoxBerryPoppinsPlugin\Controller\SettingsController'
  action: 'storeSettings'

#  Full configuration could look like this:
#  someRoute:
#    route: '/'
#    controller: 'LoxBerryPoppinsPlugin\Controller\SomeController'
#    method: 'GET,POST' <- GET is assumed if not provided
#    public: true <- false is assumed if not provided
